if(NOT DEFINED INPUT)
  message(FATAL_ERROR "EmbedNNUE.cmake requires INPUT variable")
endif()
if(NOT DEFINED OUTPUT)
  message(FATAL_ERROR "EmbedNNUE.cmake requires OUTPUT variable")
endif()
if(NOT DEFINED SYMBOL)
  message(FATAL_ERROR "EmbedNNUE.cmake requires SYMBOL variable")
endif()

file(READ "${INPUT}" _nnue_hex HEX)
if(NOT _nnue_hex)
  message(FATAL_ERROR "Failed to read binary data from ${INPUT}")
endif()

string(REGEX MATCHALL ".." _nnue_bytes "${_nnue_hex}")
set(_nnue_source "/* Generated from ${INPUT} */\n#include <stddef.h>\n#include <stdint.h>\n\nconst unsigned char ${SYMBOL}[] = {\n")
set(_nnue_line "")
set(_nnue_count 0)
foreach(_byte IN LISTS _nnue_bytes)
  if(_nnue_line STREQUAL "")
    set(_nnue_line "    0x${_byte}")
  else()
    set(_nnue_line "${_nnue_line}, 0x${_byte}")
  endif()
  math(EXPR _nnue_mod "${_nnue_count} % 16")
  if(_nnue_mod EQUAL 15)
    set(_nnue_source "${_nnue_source}${_nnue_line},\n")
    set(_nnue_line "")
  endif()
  math(EXPR _nnue_count "${_nnue_count} + 1")
endforeach()
if(NOT _nnue_line STREQUAL "")
  set(_nnue_source "${_nnue_source}${_nnue_line}\n")
endif()
set(_nnue_source "${_nnue_source}};\n\nconst size_t ${SYMBOL}_size = sizeof(${SYMBOL});\n")

file(WRITE "${OUTPUT}" "${_nnue_source}")
